server:
  port: 8080

logging:
  level:
    ROOT: INFO
    az.kapitalbank.tg: DEBUG

spring:
  application:
    name: ms-card-order
  rabbitmq:
    virtual-host: /
    host: localhost
    port: 5672
    username: guest
    password: guest
  liquibase:
    change-log: classpath:config/liquibase/changelog-master.xml
  datasource:
    url: jdbc:postgresql://localhost:5432/cms_cardorder_db
    username: cardorder_admin
    password: admin123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false  #look what is it
    generate-ddl: true
    naming: #look what is it
      physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy

application:
  swagger:
    base-package: "az.company.cardorder.controller"
    paths: "/.*"
    apiInfo:
      version: 1.0
      title: "Card Management System Rest API"
      description: "Spring Boot REST API for CArd Management System"
      termsOfServiceUrl:
      license: "Apache License Version 2.0"
      licenseUrl: "https://www.apache.org/licenses/LICENSE-2.0"
      contact:
        name: "Jalal Mehdiyev"
        email: "djalal.mekhtiyev@gmail.com"
        phone: "+994507991228"
  security:
    authentication:
      jwt:
        base64-secret: QjJCX1BBWU1FTlRfU09MVVRJT05THDSGIGDSUGAISdHOo123dSDSDADIOSUDSIUGFVSDSDsWC2sda41SADSDVDASDV==
        token-validity-in-seconds: 900
  client:
    ms-customer:
      url: http://localhost:8083