server:
  port: 8080

logging:
  level:
    ROOT: INFO
    az.kapitalbank.tg: DEBUG

spring:
  application:
    name: ms-card

application:
  swagger:
    base-package: "az.company.card.controller"
    paths: "/.*"
    apiInfo:
      version: 1.0
      title: "Starter Project Rest API"
      description: "Spring Boot REST API for Starter Project"



